apiVersion: apps/v1 # API version for Deployment resources
kind: Deployment # Specifies that we are defining a Deployment
metadata:
  name: go-k8s-server # Name of the deployment
spec:
  replicas: 3 # Number of Pod replicas to maintain
  selector:
    matchLabels:
      app: go-k8s-server # Selects Pods with this label
  template: # Define our Pods
    metadata:
      labels:
        app: go-k8s-server # Labels assigned to Pods (must match the selector above)
    spec:
      containers:
        - name: go-k8s-server
          image: go-server:latest # Image to run in the container.
          imagePullPolicy: IfNotPresent # Use local image if available.
          ports:
             - containerPort: 8080 # Port the container listens on.