apiVersion: v1
kind: Service
metadata:
  name: go-k8s-server
spec:
  # A NodePort service exposes the service on each Node's IP at the NodePort.
  type: NodePort
  selector:
    app: go-k8s-server
  ports:
    # The service will listen on port 80 and forward traffic to the target port 8080 on the pods.
    # The NodePort will be 30000, which can be accessed via the Node's IP address.
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30000