apiVersion: v1 # API version for Service resources
kind: Service # Specifies that we are defining a Service
metadata:
  name: go-k8s-server # Name of the service
spec:
  type: NodePort # Expose the service on a static port on every node in the cluster.
  selector:
    app: go-k8s-server # Selects Pods with this label
  ports:
    - name: http
      port: 80 # Listen on port 80
      targetPort: 8080 # Forward traffic to port 8080 on the pods.
      nodePort: 30000 # Define the port opened on the node.
