apiVersion: v1 # API version for Service resources
kind: Service # Specifies that we are defining a Service
metadata:
  name: go-k8s-server # Name of the service
spec:
  type: NodePort # A NodePort service exposes the service on each Node's IP at the NodePort.
  selector:
    app: go-k8s-server # Selects Pods with this label to route traffic to.
  ports:
    # The service will listen on port 80 and forward traffic to the target port 8080 on the pods.
    # The NodePort will be 30000, which can be accessed via the Node's IP address.
    - name: http
      port: 80 # Port that the service will expose
      targetPort: 8080 # Port on the Pod that the service will forward traffic to
      nodePort: 30000 # Port on each Node that will route to the service